name: Run linter and formatter on push

on: [push, pull_request]

jobs:
  lint:
    name: Run linters and formatters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - uses: borales/actions-yarn@v4
        with:
          cmd: build
      - uses: borales/actions-yarn@v4
        with:
          cmd: format
      - uses: borales/actions-yarn@v4
        with:
          cmd: lint
